### ISSUE TITLE
cicrular dependency

### ISSUE THREAD

**Issue by IvanLotoff** [hendisantika/spring-boot-kotlin-keycloak-demo#1]
The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  webSecurityConfig (field private org.keycloak.adapters.KeycloakConfigResolver org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter.keycloakConfigResolver)
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by hendisantika** [comment]
But, It was OK & Running well on my local.

**Comment by hendisantika** [comment]
Maybe you can pull latest code and let me know if there is an issue.
